#cloud-config

users:
- name: twimlrag
  uid: 2000

write_files:
  - path: /etc/systemd/system/install-gpu.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Install GPU drivers
      Wants=gcr-online.target docker.socket
      After=gcr-online.target docker.socket

      [Service]
      User=root
      Type=oneshot
      ExecStart=cos-extensions install gpu
      StandardOutput=journal+console
      StandardError=journal+console

  - path: /etc/systemd/system/twiml-rag.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Run the twiml-rag GPU application container
      Requires=install-gpu.service
      After=install-gpu.service

      [Service]
      User=root
      Type=oneshot
      RemainAfterExit=true
      ExecStart=/usr/bin/docker run \
        --volume /var/lib/nvidia/lib64:/usr/local/nvidia/lib64 \
        --volume /var/lib/nvidia/bin:/usr/local/nvidia/bin \
        --device /dev/nvidia0:/dev/nvidia0 \
        --device /dev/nvidia-uvm:/dev/nvidia-uvm \
        --device /dev/nvidiactl:/dev/nvidiactl \
        --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
        --rm -u 2000 --name=twiml-rag-container us-central1-docker.pkg.dev/twiml-rag/twiml-rag-repo/twiml-rag-stt-image:nvcr-base-no-preload
      StandardOutput=journal+console
      StandardError=journal+console

runcmd:
  - systemctl daemon-reload
  - systemctl start install-gpu.service
  - systemctl start twiml-rag.service
