[pinecone-embeddings]
EMBEDDING_MODEL = "multi-qa-mpnet-base-dot-v1"
EMBEDDING_DIMENSIONS = 768 # just used for reference atm

[openai-conversation]
VECTOR_TOP_P = 8

[streamlit-application]
MEMORY_K = 5