FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /python-docker

RUN python3 --version
RUN which python3
RUN python3 -m torch.utils.collect_env
RUN nvcc --version