FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

# FROM nvcr.io/nvidia/pytorch:24.02-py3

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /python-docker

RUN python3 --version
RUN which python3
RUN python3 -m torch.utils.collect_env
RUN python3 -c 'import torch; print("CUDA is available: ", torch.cuda.is_available())'

RUN nvcc --version